In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
a.ndim

2

In [5]:
a.shape

(3, 3)

In [6]:
a.size

9

In [7]:
a[:, 2]

array([3, 6, 9])

In [8]:
a[2,:]

array([7, 8, 9])

In [9]:
2 * np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [10]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out

array([1, 2])